apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-locust-cm"
  labels:
    app: "{{ .Release.Name }}-locust"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  ATTACKED_HOST: {{ .Values.attackhost }}